# Generated by Django 3.2.13 on 2022-04-30 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tgbot', '0004_auto_20220501_0141'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='certificate',
            field=models.ImageField(blank=True, null=True, upload_to='certificates'),
        ),
        migrations.AddField(
            model_name='user',
            name='diploma',
            field=models.ImageField(blank=True, null=True, upload_to='diplomas'),
        ),
        migrations.AddField(
            model_name='user',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='contestants'),
        ),
    ]
